import { defineStore } from 'pinia'
import useAxios from '@/composables/useAxios'
import { Field, SportCenter } from '@/types'

interface AppStore {
  sportCenters: SportCenter[]
  fields: Field[]
}

const { axiosInstance } = useAxios()

export default defineStore({
  id: 'app',
  state: () =>
    ({
      sportCenters: [
        {
          '@id': '/sport_centers/2',
          '@type': 'SportCenter',
          id: 2,
          reference: 1,
          name: 'Fútbol Arena',
          address: 'Rue du brotteaux',
          postCode: '69540',
          city: 'Irigny',
          phone: '09 82 58 12 75',
          website: 'http://www.futbol-arena.com/',
          facebookPage: 'https://www.facebook.com/Futbol-Arena-244057585640863/',
          coordinates: ['45.6848149', '4.8298567'],
          timeZone: 'Europe/Paris',
          createdAt: '2021-05-14T12:19:10+00:00',
          updatedAt: '2022-04-07T11:01:26+00:00',
        },
        {
          '@id': '/sport_centers/3',
          '@type': 'SportCenter',
          id: 3,
          reference: 2,
          name: '5 de légende',
          address: '19 Avenue des bruyères',
          postCode: '69380',
          city: 'Décines Charpieu',
          phone: '09 83 57 85 15',
          website: 'https://www.le5delegende.com/',
          facebookPage: 'https://www.facebook.com/Le-5-de-l%C3%A9gende-912140905519410/',
          coordinates: ['45.761487', '4.941259'],
          timeZone: 'Europe/Paris',
          createdAt: '2021-05-14T12:19:10+00:00',
          updatedAt: '2022-03-24T12:35:31+00:00',
        },
        {
          '@id': '/sport_centers/4',
          '@type': 'SportCenter',
          id: 4,
          reference: 3,
          name: 'Universal Soccer',
          address: '327 Chemin des plantades',
          postCode: '83130',
          city: 'Toulon',
          phone: '04 94 91 01 97',
          website: 'http://www.universalsoccer.fr/',
          facebookPage: 'https://www.facebook.com/Universal-Soccer-132561886796815/',
          coordinates: ['43.14315', '6.0274717'],
          timeZone: 'Europe/Paris',
          createdAt: '2021-05-14T12:19:10+00:00',
          updatedAt: '2021-12-29T13:09:07+00:00',
        },
        {
          '@id': '/sport_centers/5',
          '@type': 'SportCenter',
          id: 5,
          reference: 4,
          name: 'Street 5',
          address: "30 Rue de l'artisanat",
          postCode: '21560',
          city: 'Couternon',
          phone: '03 80 32 07 88',
          website: 'http://www.street5futbol.com/',
          facebookPage: 'https://www.facebook.com/Street-5-139238269903931/',
          coordinates: ['47.3224542', '5.1244749'],
          timeZone: 'Europe/Paris',
          createdAt: '2021-05-14T12:19:10+00:00',
          updatedAt: '2022-01-03T14:37:53+00:00',
        },
        {
          '@id': '/sport_centers/7',
          '@type': 'SportCenter',
          id: 7,
          reference: 5,
          name: 'Player 5M',
          address: 'ZAC la Capucière',
          postCode: '34550',
          city: 'Bessan',
          phone: '06 81 24 11 06',
          website: 'http://player5m.free.fr/',
          facebookPage: 'https://www.facebook.com/ludo.futsal.7',
          coordinates: ['43.3732096', '3.4224907'],
          timeZone: 'Europe/Paris',
          createdAt: '2021-05-14T12:19:10+00:00',
          updatedAt: '2021-12-29T12:08:20+00:00',
        },
        {
          '@id': '/sport_centers/8',
          '@type': 'SportCenter',
          id: 8,
          reference: 6,
          name: 'Le temple du foot',
          address: '5 Rue du Stade',
          postCode: '76140',
          city: 'Le Petit-Quevilly',
          phone: '02 35 62 81 25',
          website: 'https://letempledufootrouen.fr/',
          facebookPage: 'https://www.facebook.com/pages/Temple-Du-Foot/101988893199555',
          coordinates: ['49.4266694', '1.049394'],
          timeZone: 'Europe/Paris',
          createdAt: '2021-05-14T12:19:10+00:00',
          updatedAt: '2021-05-14T12:19:10+00:00',
        },
        {
          '@id': '/sport_centers/9',
          '@type': 'SportCenter',
          id: 9,
          reference: 7,
          name: 'Soccer Club Vichy',
          address: '18 Avenue de la croix St Martin',
          postCode: '03200',
          city: 'Vichy',
          phone: '04 70 41 26 56',
          website: 'http://www.soccerclub.fr/fr/foot-en-salle/vichy/soccer_club_vichy',
          facebookPage: 'https://www.facebook.com/soccerclubvichy',
          coordinates: ['46.1147642', '3.4348346'],
          timeZone: 'Europe/Paris',
          createdAt: '2021-05-14T12:19:10+00:00',
          updatedAt: '2022-01-03T14:36:24+00:00',
        },
        {
          '@id': '/sport_centers/10',
          '@type': 'SportCenter',
          id: 10,
          reference: 8,
          name: 'Esprit Padel',
          address: '155 Route de Grenoble',
          postCode: '69800',
          city: 'Saint-Priest',
          phone: '09 63 58 76 15',
          website: 'http://espritpadel.com/',
          facebookPage: 'https://www.facebook.com/EspritPadel/',
          coordinates: ['45.710895', '4.974430'],
          timeZone: 'Europe/Paris',
          createdAt: '2021-05-14T12:19:10+00:00',
          updatedAt: '2022-01-06T08:32:01+00:00',
        },
        {
          '@id': '/sport_centers/11',
          '@type': 'SportCenter',
          id: 11,
          reference: 9,
          name: 'Pro Soccer 5',
          address: '17 Rue Irène Joliot Curie',
          postCode: '38320',
          city: 'Eybens',
          phone: '09 84 47 27 27',
          website: 'https://prosoccer5.fr/',
          facebookPage: 'https://www.facebook.com/prosoccer5/',
          coordinates: ['45.149065', '5.736550'],
          timeZone: 'Europe/Paris',
          createdAt: '2021-05-14T12:19:10+00:00',
          updatedAt: '2022-05-03T08:36:05+00:00',
        },
        {
          '@id': '/sport_centers/12',
          '@type': 'SportCenter',
          id: 12,
          reference: 10,
          name: 'Mont Foot 5',
          address: '14 Rue Gustave Eiffel',
          postCode: '74600',
          city: 'Seynod',
          phone: '04 50 44 94 76',
          website: 'http://www.montfoot5annecy.fr/',
          facebookPage: 'https://www.facebook.com/montfoot5/',
          coordinates: ['45.885740', '6.074029'],
          timeZone: 'Europe/Paris',
          createdAt: '2021-05-14T12:19:10+00:00',
          updatedAt: '2022-05-06T15:08:48+00:00',
        },
      ],
      fields: [
        {
          '@id': '/fields/1',
          '@type': 'Field',
          id: 1,
          reference: 1,
          name: 'Terrain 3',
          ngtvOffer: 'ec1',
          fiveId: null,
          sportCenter: {
            '@id': '/sport_centers/2',
            '@type': 'SportCenter',
            id: 2,
            reference: 1,
            name: 'Fútbol Arena',
            address: 'Rue du brotteaux',
            timeZone: 'Europe/Paris',
            createdAt: '2021-05-14T12:19:10+00:00',
            updatedAt: '2022-04-07T11:01:26+00:00',
          },
          sport: {
            '@id': '/sports/1',
            '@type': 'Sport',
            id: 1,
            name: 'Football',
            racketSport: false,
          },
          cameras: [
            {
              '@id': '/cameras/11',
              '@type': 'Camera',
              id: 11,
              url: 'rtsp://admin:NGTV@ngtv@192.168.2.111:554/cam/realmonitor?channel=1&subtype=0',
            },
            {
              '@id': '/cameras/12',
              '@type': 'Camera',
              id: 12,
              url: 'rtsp://admin:NGTV@ngtv@192.168.2.112:554/cam/realmonitor?channel=1&subtype=0',
            },
            {
              '@id': '/cameras/13',
              '@type': 'Camera',
              id: 13,
              url: 'rtsp://admin:NGTV@ngtv@192.168.2.113:554/cam/realmonitor?channel=1&subtype=0',
            },
            {
              '@id': '/cameras/14',
              '@type': 'Camera',
              id: 14,
              url: 'rtsp://admin:NGTV@ngtv@192.168.2.114:554/cam/realmonitor?channel=1&subtype=0',
            },
          ],
          createdAt: '2021-05-14T12:19:10+00:00',
          updatedAt: '2022-03-21T11:37:21+00:00',
        },
        {
          '@id': '/fields/3',
          '@type': 'Field',
          id: 3,
          reference: 3,
          name: 'Terrain 1',
          ngtvOffer: 'none',
          fiveId: null,
          sportCenter: {
            '@id': '/sport_centers/2',
            '@type': 'SportCenter',
            id: 2,
            reference: 1,
            name: 'Fútbol Arena',
            address: 'Rue du brotteaux',
            timeZone: 'Europe/Paris',
            createdAt: '2021-05-14T12:19:10+00:00',
            updatedAt: '2022-04-07T11:01:26+00:00',
          },
          sport: {
            '@id': '/sports/1',
            '@type': 'Sport',
            id: 1,
            name: 'Football',
            racketSport: false,
          },
          cameras: [],
          createdAt: '2021-05-14T12:19:10+00:00',
          updatedAt: '2022-03-21T11:22:50+00:00',
        },
        {
          '@id': '/fields/4',
          '@type': 'Field',
          id: 4,
          reference: 4,
          name: 'Terrain 2',
          ngtvOffer: null,
          fiveId: null,
          sportCenter: {
            '@id': '/sport_centers/2',
            '@type': 'SportCenter',
            id: 2,
            reference: 1,
            name: 'Fútbol Arena',
            address: 'Rue du brotteaux',
            timeZone: 'Europe/Paris',
            createdAt: '2021-05-14T12:19:10+00:00',
            updatedAt: '2022-04-07T11:01:26+00:00',
          },
          sport: {
            '@id': '/sports/1',
            '@type': 'Sport',
            id: 1,
            name: 'Football',
            racketSport: false,
          },
          cameras: [],
          createdAt: '2021-05-14T12:19:10+00:00',
          updatedAt: '2021-05-14T12:19:10+00:00',
        },
        {
          '@id': '/fields/7',
          '@type': 'Field',
          id: 7,
          reference: 7,
          name: 'Terrain 4',
          ngtvOffer: null,
          fiveId: null,
          sportCenter: {
            '@id': '/sport_centers/2',
            '@type': 'SportCenter',
            id: 2,
            reference: 1,
            name: 'Fútbol Arena',
            address: 'Rue du brotteaux',
            timeZone: 'Europe/Paris',
            createdAt: '2021-05-14T12:19:10+00:00',
            updatedAt: '2022-04-07T11:01:26+00:00',
          },
          sport: {
            '@id': '/sports/1',
            '@type': 'Sport',
            id: 1,
            name: 'Football',
            racketSport: false,
          },
          cameras: [],
          createdAt: '2021-05-14T12:19:10+00:00',
          updatedAt: '2021-05-14T12:19:10+00:00',
        },
      ],
      sessions: [
        {
          '@id': '/ngtv_sessions/193874',
          '@type': 'NgtvSession',
          id: 193874,
          name: 'JESUDASAN',
          reference: '6290715e73cf6350389508',
          plannedStartedAt: '2022-05-27T11:00:00+00:00',
          localPlannedStartedAt: '2022-05-27T11:00:00+00:00',
          plannedEndedAt: '2022-05-27T12:00:00+00:00',
          plannedDuration: 3600,
          actualStartedAt: '2022-05-27T11:02:35+00:00',
          localActualStartedAt: '2022-05-27T11:02:35+00:00',
          actualEndedAt: '2022-05-27T11:59:59+00:00',
          actualDuration: 3444,
          videoSources: ['https://v1.ngtvexperience.com/uploads/ec1_sessions/6290715e73cf6350389508/video0.mp4'],
          hasVideoVisible: true,
          competitionStage: null,
          competitionRoundId: null,
          events: [],
          competitionBreakDuration: null,
          zonesActivityPercentages: [],
          status: 'played',
          videoURLs: [],
          field: {
            '@id': '/fields/304',
            '@type': 'Field',
            id: 304,
            reference: 304,
            name: 'Terrain NGTV',
            ngtvOffer: 'ec1',
            sportCenter: {
              '@id': '/sport_centers/120',
              '@type': 'SportCenter',
              id: 120,
              reference: 120,
              name: 'Basket Center Strasbourg',
              timeZone: 'Europe/Paris',
              createdAt: '2021-10-07T09:09:06+00:00',
              updatedAt: '2021-10-28T12:55:44+00:00',
            },
            sport: {
              '@id': '/sports/5',
              '@type': 'Sport',
              id: 5,
              name: 'Basketball',
              racketSport: false,
            },
            createdAt: '2021-10-07T09:41:11+00:00',
            updatedAt: '2021-10-27T13:12:22+00:00',
          },
          ngtvSessionType: {
            '@id': '/ngtv_session_types/1',
            '@type': 'NgtvSessionType',
            id: 1,
            name: 'EasyConnect',
            reference: 'easy-connect',
          },
          competition: null,
          createdAt: '2022-05-27T10:00:00+00:00',
          updatedAt: '2022-05-27T23:38:06+00:00',
          ngtvSessionHomeTeam: {
            '@id': '/ngtv_session_teams/371337',
            '@type': 'NgtvSessionTeam',
            id: 371337,
            color: 'orange',
            home: true,
            fullScore: [0],
            maxInvincibilityDuration: 3444,
            maxConsecutiveGoals: 0,
            possession: 0,
            forfeit: false,
            team: null,
            createdAt: '2022-05-27T10:00:00+00:00',
            updatedAt: '2022-05-27T10:00:00+00:00',
            score: 0,
          },
          ngtvSessionAwayTeam: {
            '@id': '/ngtv_session_teams/371338',
            '@type': 'NgtvSessionTeam',
            id: 371338,
            color: 'blue',
            home: false,
            fullScore: [0],
            maxInvincibilityDuration: 3444,
            maxConsecutiveGoals: 0,
            possession: 0,
            forfeit: false,
            team: null,
            createdAt: '2022-05-27T10:00:00+00:00',
            updatedAt: '2022-05-27T10:00:00+00:00',
            score: 0,
          },
        },
      ],
      session: {
        '@id': '/ngtv_sessions/82322',
        '@type': 'NgtvSession',
        id: 82322,
        name: '202107262005114',
        reference: '202107262005114',
        plannedStartedAt: '2021-07-26T20:05:00+00:00',
        localPlannedStartedAt: '2021-07-26T20:05:00+00:00',
        plannedEndedAt: '2021-07-26T21:04:46+00:00',
        plannedDuration: 3586,
        actualStartedAt: '2021-07-26T20:05:00+00:00',
        localActualStartedAt: '2021-07-26T20:05:00+00:00',
        actualEndedAt: '2021-07-26T21:04:46+00:00',
        actualDuration: 3586,
        videoSources: ['https://v1.ngtvexperience.com/uploads/session/202107262005114/3cb3a9d65b41829f8ddc2cde81218990.mp4'],
        hasVideoVisible: true,
        competitionStage: null,
        competitionRoundId: null,
        events: [
          {
            matchTimecode: 35,
            videoTimecode: 35,
            type: 'goal',
            team: 'home',
            scoreHome: 1,
            scoreAway: 0,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 209,
            videoTimecode: 209,
            type: 'goal',
            team: 'home',
            scoreHome: 2,
            scoreAway: 0,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 229,
            videoTimecode: 229,
            type: 'goal',
            team: 'away',
            scoreHome: 2,
            scoreAway: 1,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 342,
            videoTimecode: 342,
            type: 'goal',
            team: 'home',
            scoreHome: 3,
            scoreAway: 1,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 360,
            videoTimecode: 360,
            type: 'goal',
            team: 'away',
            scoreHome: 3,
            scoreAway: 2,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 407,
            videoTimecode: 407,
            type: 'goal',
            team: 'home',
            scoreHome: 4,
            scoreAway: 2,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 430,
            videoTimecode: 430,
            type: 'goal',
            team: 'away',
            scoreHome: 4,
            scoreAway: 3,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 500,
            videoTimecode: 500,
            type: 'goal',
            team: 'away',
            scoreHome: 4,
            scoreAway: 4,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 544,
            videoTimecode: 544,
            type: 'goal',
            team: 'home',
            scoreHome: 5,
            scoreAway: 4,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 816,
            videoTimecode: 816,
            type: 'goal',
            team: 'away',
            scoreHome: 5,
            scoreAway: 5,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 851,
            videoTimecode: 851,
            type: 'goal',
            team: 'away',
            scoreHome: 5,
            scoreAway: 6,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 986,
            videoTimecode: 986,
            type: 'goal',
            team: 'home',
            scoreHome: 6,
            scoreAway: 6,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 1040,
            videoTimecode: 1040,
            type: 'goal',
            team: 'home',
            scoreHome: 7,
            scoreAway: 6,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 1072,
            videoTimecode: 1072,
            type: 'goal',
            team: 'away',
            scoreHome: 7,
            scoreAway: 7,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 1139,
            videoTimecode: 1139,
            type: 'goal',
            team: 'home',
            scoreHome: 8,
            scoreAway: 7,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 1227,
            videoTimecode: 1227,
            type: 'goal',
            team: 'home',
            scoreHome: 9,
            scoreAway: 7,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 1315,
            videoTimecode: 1315,
            type: 'goal',
            team: 'away',
            scoreHome: 9,
            scoreAway: 8,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 1399,
            videoTimecode: 1399,
            type: 'goal',
            team: 'home',
            scoreHome: 10,
            scoreAway: 8,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 1531,
            videoTimecode: 1531,
            type: 'goal',
            team: 'away',
            scoreHome: 10,
            scoreAway: 9,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 1957,
            videoTimecode: 1957,
            type: 'goal',
            team: 'home',
            scoreHome: 11,
            scoreAway: 9,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 1989,
            videoTimecode: 1989,
            type: 'goal',
            team: 'home',
            scoreHome: 12,
            scoreAway: 9,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2042,
            videoTimecode: 2042,
            type: 'goal',
            team: 'home',
            scoreHome: 13,
            scoreAway: 9,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2141,
            videoTimecode: 2141,
            type: 'goal',
            team: 'home',
            scoreHome: 14,
            scoreAway: 9,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2176,
            videoTimecode: 2176,
            type: 'goal',
            team: 'home',
            scoreHome: 15,
            scoreAway: 9,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2197,
            videoTimecode: 2197,
            type: 'goal',
            team: 'home',
            scoreHome: 16,
            scoreAway: 9,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2249,
            videoTimecode: 2249,
            type: 'goal',
            team: 'home',
            scoreHome: 17,
            scoreAway: 9,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2395,
            videoTimecode: 2395,
            type: 'goal',
            team: 'home',
            scoreHome: 18,
            scoreAway: 9,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2446,
            videoTimecode: 2446,
            type: 'goal',
            team: 'away',
            scoreHome: 18,
            scoreAway: 10,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2539,
            videoTimecode: 2539,
            type: 'goal',
            team: 'home',
            scoreHome: 19,
            scoreAway: 10,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2577,
            videoTimecode: 2577,
            type: 'goal',
            team: 'home',
            scoreHome: 20,
            scoreAway: 10,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2672,
            videoTimecode: 2672,
            type: 'goal',
            team: 'home',
            scoreHome: 21,
            scoreAway: 10,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2717,
            videoTimecode: 2717,
            type: 'goal',
            team: 'away',
            scoreHome: 21,
            scoreAway: 11,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2740,
            videoTimecode: 2740,
            type: 'goal',
            team: 'home',
            scoreHome: 22,
            scoreAway: 11,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2779,
            videoTimecode: 2779,
            type: 'goal',
            team: 'home',
            scoreHome: 23,
            scoreAway: 11,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2824,
            videoTimecode: 2824,
            type: 'goal',
            team: 'away',
            scoreHome: 23,
            scoreAway: 12,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2918,
            videoTimecode: 2918,
            type: 'goal',
            team: 'home',
            scoreHome: 24,
            scoreAway: 12,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2942,
            videoTimecode: 2942,
            type: 'goal',
            team: 'home',
            scoreHome: 25,
            scoreAway: 12,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 2966,
            videoTimecode: 2966,
            type: 'goal',
            team: 'away',
            scoreHome: 25,
            scoreAway: 13,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 3057,
            videoTimecode: 3057,
            type: 'goal',
            team: 'home',
            scoreHome: 26,
            scoreAway: 13,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 3254,
            videoTimecode: 3254,
            type: 'goal',
            team: 'home',
            scoreHome: 27,
            scoreAway: 13,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 3320,
            videoTimecode: 3320,
            type: 'goal',
            team: 'home',
            scoreHome: 28,
            scoreAway: 13,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 3472,
            videoTimecode: 3472,
            type: 'goal',
            team: 'home',
            scoreHome: 29,
            scoreAway: 13,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 3530,
            videoTimecode: 3530,
            type: 'goal',
            team: 'away',
            scoreHome: 29,
            scoreAway: 14,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
          {
            matchTimecode: 3574,
            videoTimecode: 3574,
            type: 'goal',
            team: 'away',
            scoreHome: 29,
            scoreAway: 15,
            playerTeamId: null,
            secondPlayerTeamId: null,
            playerId: null,
            teamId: null,
            secondPlayerId: null,
            secondTeamId: null,
            ngtvSessionPlayerReference: null,
            secondNgtvSessionPlayerReference: null,
            playerName: null,
            secondPlayerName: null,
          },
        ],
        competitionBreakDuration: null,
        zonesActivityPercentages: ['0.08', '0.27', '0.42', '0.23'],
        status: 'exported_deleted',
        videoURLs: null,
        field: {
          '@id': '/fields/114',
          '@type': 'Field',
          id: 114,
          reference: 114,
          name: 'Terrain 2',
          ngtvOffer: 'hi5',
          sportCenter: {
            '@id': '/sport_centers/43',
            '@type': 'SportCenter',
            id: 43,
            reference: 43,
            name: 'Auréats FootIndoor',
            timeZone: 'Europe/Paris',
            createdAt: '2021-05-14T12:19:10+00:00',
            updatedAt: '2021-12-15T10:30:05+00:00',
          },
          sport: {
            '@id': '/sports/1',
            '@type': 'Sport',
            id: 1,
            name: 'Football',
            racketSport: false,
          },
          createdAt: '2021-05-14T12:19:10+00:00',
          updatedAt: '2021-12-15T09:45:26+00:00',
        },
        ngtvSessionType: {
          '@id': '/ngtv_session_types/2',
          '@type': 'NgtvSessionType',
          id: 2,
          name: 'Hi5',
          reference: 'hi5',
        },
        competition: null,
        createdAt: '2021-07-27T09:06:20+00:00',
        updatedAt: '2021-09-09T14:28:41+00:00',
        ngtvSessionHomeTeam: {
          '@id': '/ngtv_session_teams/160649',
          '@type': 'NgtvSessionTeam',
          id: 160649,
          color: 'orange',
          home: true,
          fullScore: [29],
          maxInvincibilityDuration: 915,
          maxConsecutiveGoals: 8,
          possession: 0,
          forfeit: false,
          team: null,
          createdAt: '2021-07-27T09:06:19+00:00',
          updatedAt: '2021-09-09T14:28:41+00:00',
          score: 29,
        },
        ngtvSessionAwayTeam: {
          '@id': '/ngtv_session_teams/160650',
          '@type': 'NgtvSessionTeam',
          id: 160650,
          color: 'blue',
          home: false,
          fullScore: [15],
          maxInvincibilityDuration: 558,
          maxConsecutiveGoals: 2,
          possession: 0,
          forfeit: false,
          team: null,
          createdAt: '2021-07-27T09:06:19+00:00',
          updatedAt: '2021-09-09T14:28:41+00:00',
          score: 15,
        },
      },
    } as any),
  actions: {
    async getSportCenters() {
      try {
        // const { data } = await axiosInstance().get('/sport_centers?tags.reference=powerleague')
        const { data } = await axiosInstance().get('/sport_centers')

        this.$patch({
          sportCenters: data['hydra:member'],
        })
      } catch (e: any) {
        // ...
      }
    },
    async getFields(sportCenterId: number | undefined) {
      try {
        const { data } = await axiosInstance().get(`/fields?sportCenter.id=${sportCenterId}`)

        this.$patch({
          sportCenters: data['hydra:member'],
        })
      } catch (e: any) {
        // ...
      }
    },
    // async getSessions(payload: SessionPayload) {
    //   try {
    //     const { data } = await axiosInstance().get(`/fields?sportCenter.id=${sportCenterId}`)

    //     this.$patch({
    //       sportCenters: data['hydra:member'],
    //     })
    //   } catch (e: any) {
    //     // ...
    //   }
    // },
    async getSessionBySessionId(sessionId: string | string[]) {
      try {
        const { data } = await axiosInstance().get(`/ngtv_sessions/${sessionId}`)

        this.$patch({
          session: data,
        })
      } catch (e: any) {
        // ...
      }
    },
  },
})
